package: conda-env
user: conda

platform:
  - linux-32
  - linux-64
  - win-32
  - win-64
  # - osx-64

engine:
  - python=2
  - python=3

# Can't test on binstar because it needs to be installed in root
script:
  - conda build --no-test ./conda.recipe/

build_targets: conda
