package:
  name: conda-env
  version: 1.2.0alpha

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}
  preserve_egg_dir: yes

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

about:
  home: https://github.com/conda/conda-env/
